// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPl4GDwbj-VNMBuX5XgcV8lVzDOuY-jN4',
    appId: '1:484048731524:web:fed27c35e7f1afee60b1d1',
    messagingSenderId: '484048731524',
    projectId: 'agora-641bc',
    authDomain: 'agora-641bc.firebaseapp.com',
    storageBucket: 'agora-641bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmIEEei32YNgme2CWN52owS6gL-4q5gik',
    appId: '1:484048731524:android:e380cc1ea94b8fd160b1d1',
    messagingSenderId: '484048731524',
    projectId: 'agora-641bc',
    storageBucket: 'agora-641bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaga2wCZAAZc7d5lHbNEBUcS7JgoXqZW8',
    appId: '1:484048731524:ios:54d2d3967d87da7360b1d1',
    messagingSenderId: '484048731524',
    projectId: 'agora-641bc',
    storageBucket: 'agora-641bc.appspot.com',
    iosClientId: '484048731524-pndq6i7c44cu1ubt4namo42cgi3nqerr.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdfdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaga2wCZAAZc7d5lHbNEBUcS7JgoXqZW8',
    appId: '1:484048731524:ios:e93b4a8ad7eead5b60b1d1',
    messagingSenderId: '484048731524',
    projectId: 'agora-641bc',
    storageBucket: 'agora-641bc.appspot.com',
    iosClientId: '484048731524-33u2qjnbj68se25fafaipmahmefv4ldn.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdfdemo.RunnerTests',
  );
}
